### ISSUE TITLE
No information about build system etc

### ISSUE THREAD

**Issue by gpaluk** [fritx/react-threejs#2]
There is no information about building and running this locally and no information about the dependency chain etc.

**Comment by fritx** [comment]
@PluginIO apology for the missing docs.
I just tried to run it myself, and forgot everything. :joy:

1. Build system

    People can always find bulid scripts in package.json,
    it is very implicit though:

    https://github.com/fritx/react-threejs/blob/0dc041711af189cc6f676a1964a07729d1bc4809/package.json#L6-L9

2. Run locally

    For now, the project doesn't provide you a dev-server or static-sever.
    The webpack's version is 1.x, and it just builds the dist.
    You have to setup a static server to see the demo yourself like:

    ```sh
    npm i -g serve
    serve .
    open https://localhost:5000
    ```

**Comment by gpaluk** [comment]
Thanks for responding quickly. I followed the instructions above, and got a blank page. When I launch the browser at localhost:5000 I see the folder structure. I opened the example folder and index page source, I can see a link to dist.js however when I click it, that is missing. So I think there was a missing build step?

**Comment by fritx** [comment]
@PluginIO yeah, as I pasted above, you have to run `npm run dev`, which outputs `example/dist.js`.
It would keep watching our source files, so you can refresh the page everytime after modification.

**Comment by fritx** [comment]
Thanks for giving it a try! Now I spend more time on vue-threejs, it is more advanced in progress.
Later if possible, I will try my best to keep react-threejs in touch.

**Comment by gpaluk** [comment]
<img width="791" alt="screen shot 2017-09-28 at 14 58 50" src="https://user-images.githubusercontent.com/1716106/30970681-a56c0008-a45d-11e7-8445-bd2e2e404feb.png">

> npm run dev

The above line did not appear in your previous comment.

**Comment by gpaluk** [comment]
What I had to do to make this work.

Open Terminal
> git clone https://github.com/fritx/react-threejs.git
> cd react-threejs
> npm install --save-dev webpack
> npm upgrade
> npm run dev

Open new Terminal
> cd react-threejs
> npm i -g serve
> serve .

Open browser and enter the following into the address bar:
http://localhost:5000

**Comment by fritx** [comment]
@PluginIO thanks for your information!

The `webpack` did list in the package.json:
https://github.com/fritx/react-threejs/blob/0dc041711af189cc6f676a1964a07729d1bc4809/package.json#L32

You just needed to run `npm install` before `npm run dev`, my bad!

**Comment by fritx** [comment]
Any PR about the docs or code will be appreciated 😆

**Comment by gpaluk** [comment]
I think you know more than I do about your build pipeline. 😛 I've already moved on. I am stacking up fallbacks, but my end goal is to create my own environment and skeleton templates for Bridge.net, Three and React so it's unlikely that I'll be building anything directly from this template. Cheers

**Comment by fritx** [comment]
Nice, you were awesome!
I used to be a big fan of ActionScript 3 too, serveral years ago.
